### ISSUE TITLE
Duplex causes sound issues

### ISSUE THREAD

**Issue by jmaris** [duffydack/linux-max98090#2] opened 2017-10-08 16:24 UTC
Hey,
First of all, thanks again for your hard work in making this available as a convenient repository, I really appreciate it !

I've recently ran into a problem: 
when I record without playback, i have no problems.
when I playback without recording, i have no problems.
but as soon as i attempt to do both, audio is severely distorted, low, jumpy and stuttery.

I initially thought this was an issue with pulseaudio, but i went on to fully stop pulseaudio, and the issue persisted using only alsa.

Not sure what the cause is, dmesg spits out nothing of interest...

**Comment by duffydack** [comment] 2017-10-08 16:47
_sigh_.  Kernel still using older driver, which might be the problem.  Well I just streamed music and ran ffmpeg -f pulse -i default output.wav and everything sounds perfect.  What are you using?

**Comment by jmaris** [comment] 2017-10-08 16:59
With Pulseaudio, when I playback audio and run that command it breaks sound too

**Comment by duffydack** [comment] 2017-10-08 17:04
I usually only have PA set to stereo output only, and only just set to both to record that sample and it gave me that garbled output that I got now n then when plugging in headphones, which I've not had for ages..  I think the kernel will eventually fix it (add our old codec to the new driver, as they've patched the regressions, which I think entitles us to an overall fix, but we'll see.
Well, works for me and not you?  I've flashed uefi btw since last spoke, which might make a difference.

**Comment by jmaris** [comment] 2017-10-08 17:07
That's usually my setup too (to avoid accidentally garbling the audio), however with that setup the mic doesn't record! it's not the end of the world, atm i don't really record or voice chat often and can always use my phone !

**Comment by duffydack** [comment] 2017-10-08 17:09
Oh microphone, I don't have one to test.. I'm only testing stream capture.

**Comment by jmaris** [comment] 2017-10-08 17:13
ahh right ! I was testing with internal mic and with headset mic !

**Comment by duffydack** [comment] 2017-10-08 17:33
I just tested with internal mic.  I set to PA profile to multichannel duplex.  got the PLL unlock crap but fixed after I flicked the profile back n forth.  played music and internal mic picked it up, a bit low, but that might be just crap hardware (chromebook afterall).
have a listen.
https://ptpb.pw/WDun

**Comment by duffydack** [comment] 2017-10-08 17:44
You say you are using UEFI.  Do you see the boot logo 😄

**Comment by duffydack** [comment] 2017-10-08 18:28
Couple more things before I close.  Try the #pulseaudio channel on freenode irc, they've helped me out before (the bug that killed audio in PA v11.0 - that I got them to fix in 11.1.  Also, have you thought about getting a HDMI headset?  Should work perfectly.

**Comment by duffydack** [comment] 2017-10-08 19:34
You sure you had the same issue with pure alsa?  I booted my iso, removed pulseaudio and made sure it's not running, and plugging in headphones does nothing at all, not switch to them, not unmute the mixer, nothing.

**Comment by duffydack** [comment] 2017-10-08 20:06
https://www.amazon.co.uk/s/ref=nb_sb_noss/257-7842757-8663011?url=search-alias%3Daps&field-keywords=TROND+AC2+Aluminum+USB+Audio+Adapter
tidy little thing

**Comment by duffydack** [comment] 2017-10-09 09:36
'linux-git-ma98090'  (4.14) now in the repo if you like to play with bleeding edge

**Comment by duffydack** [comment] 2017-10-09 20:21
Spoke to someone on IRC, showed them all my logs and card info, they were like *wtf is this card.  Fubar*
The half assed kernel driver must be the problem.  Case closed, for now.

**Comment by duffydack** [comment] 2017-11-23 16:47
Hey.  I've only just noticed there are updated ucm files for byt-max98090 on one of the alsa devs github pages.  Why the fuck they don't include them with pulseaudio I dunno, madness... Just tried and the pll unlock/distortion is much better handled, and I have inserted headphones in and out without any 'crashing'.  Running pavucontrol seems to trigger it still for some reason.  Anyway, copy the byt-max98090 folder from https://github.com/plbossart/UCM to /usr/share/alsa/ucm/
Might wanna remove your existing /var/lib/alsa/asound.state as this gets setup already from the ucm.  Mixers are different too now, you'll see when you use it.

According to alsa-devel mailing list our chip is supposed to now use the cht driver, but it doesn't work, it just falls back to bytcht-nocodec (a new option in 4.14 config).  Fuckers can't get anything right. 

Anyway let me know how things go.

**Comment by duffydack** [comment] 2017-11-24 23:02
Hmmmmmmmm.  So, I just tested a patch that is yet to be merged, that adds the baytrail to the cherrytrail driver, so with the chtmax98090 UCM files, stock arch kernel sound works....BUT, it seems to work exactly the same in terms of pll unlock and daleks when you do certain things like run pavucontrol.  ffs.

**Comment by duffydack** [comment] 2017-11-27 11:40
Well I'm gonna miss compiling kernels, NOT.  4.15rc1 newer drivers enabled and with CONFIG_INTEL_ATOMISP enabled (which stopped sound before) and sound is working.

**Comment by JSkier21** [comment] 2017-11-28 17:25
@duffydack, with your experience testing, any changes with the built-in mic (ie, does it work)?

**Comment by duffydack** [comment] 2017-11-28 17:50
Not tested that yet.  Even using the patches to use newer driver it's still getting pll unlocks.  Not as bad maybe, depending on if you use the ucm files.  I began adding them to the pkg but changed my mind, so check if you have chtmax98090 folder in use/share/alsa/ucm , if not then grab from https://github.com/plbossart/UCM
See how they work, they'll probably be added upstream eventually on alsa anyway.

**Closed** 2018-01-30 09:22 UTC

**Comment by Jasperro** [comment] 2018-02-05 11:15
I'm not really sure, but I enabled "Record Path DC Blocking" in alsamixer and haven't had the dalek sounds when recording audio. PLL unlocks have something to do with this, no?

**Comment by duffydack** [comment] 2018-02-05 11:57
Interesting.  Do you get any pll unlock messages?  If there are any, with the newer kernels it's supposed to recover from them quick enough to not cause any issues.  I don't use/care about inputs so not tested.

**Comment by Jasperro** [comment] 2018-02-05 12:09
I don't think I get pll unlock messages. Am I supposed to look at the tty? I can record and listen at the same time.

**Comment by duffydack** [comment] 2018-02-05 12:25
journalctl -f

**Comment by Jasperro** [comment] 2018-02-05 12:27
I can't see any pll unlocks if I run that

**Comment by duffydack** [comment] 2018-02-05 12:31
And if you turn record path back off?

**Comment by Jasperro** [comment] 2018-02-05 12:51
I rebooted, which turned the setting off, and I can see pll unlocks.
feb 05 13:49:46 tostiapparaat kernel: max98090_pll_work: 198 callbacks suppressed
feb 05 13:49:46 tostiapparaat kernel: max98090 i2c-193C9890:00: PLL unlocked

**Comment by duffydack** [comment] 2018-02-05 12:58
Does it affect recording though?  It's "supposed to" recover quicky.
So it doesn't save the setting?  Odd.  You can use the ucm still, and have it enable on boot, as well as set proper volume outputs, which is what gets screwed with when using the ucm

**Comment by Jasperro** [comment] 2018-02-05 14:58
I discovered that when using the UCM, my internal microphone is enabled. Without it, it is disabled. So it looks like it recorded the monitor of the internal sound. The same issue of pll unlocks still persists with the internal mic. It looks like I wasted your time, sorry.

**Comment by duffydack** [comment] 2018-02-05 15:09
heh, no worries.  they might have 'fixed' sound in their minds, but all they did was get it back to a half working state that existed in 4.4.  if you need inputs that badly, I'd buy a cheap hdmi dongle.
