### ISSUE TITLE
Suggestion: host copy of package sources on GitHub

### ISSUE THREAD

**Issue by wheeskers** [duffydack/linux-max98090#3] opened 2017-10-11 10:19 UTC
Hi @duffydack,

Thank you for building and maintaining this, I am sure there are many people who are using this kernel because sound support for `max98090` driver in mainline is broken at the moment (at least for `4.13.5`).

A couple of questions:

1. Would you mind to host a copy of package sources *or* kernel config on GitHub? This will help other people adapt or re-build kernels for other distros or devices.
2. I am trying to reproduce your kernel config and got stuck: if I disable all SND SoC driver/codecs (except `max98090` of course) and compile kernel -- alsa and PA detect sound output but it feels like "muted" on hardware level. Enabling "Left Speaker Left DAC" and other `alsamixer` switches won't help. Where is the catch? If I boot your kernel -- it works fine (ALSA config is the same).

I like your package very much but my CB3-111 won't suspend correctly with it (no idea why -- it just works on stock kernel without reconfiguring anything), so I am trying to compile my own kernel with bare minimum modification of stock config (yes, lots of bloat drivers) to make sound output work.

**Comment by duffydack** [comment] 2017-10-11 11:03
Hi.  Yeah the kernel has been broken for AGES, but at least it no longer needs patches, they've been merged.  Just needs the kernel devs to supply a proper fix and add the older 98090 to the newer codec they made, which broke ours, and fails to build unless newer is disabled.

> Would you mind to host a copy of package sources or kernel config on GitHub? This will help other people adapt or re-build kernels for other distros or devices.

Files used to build are hosted in the AUR [https://aur.archlinux.org/cgit/aur.git/snapshot/linux-max98090.tar.gz](url)

> I am trying to reproduce your kernel config and got stuck: if I disable all SND SoC driver/codecs (except max98090 of course) and compile kernel -- alsa and PA detect sound output but it feels like "muted" on hardware level. Enabling "Left Speaker Left DAC" and other alsamixer switches won't help. Where is the catch? If I boot your kernel -- it works fine (ALSA config is the same).

The card is detected then?  What version of pulseaudio (what OS for that matter) you using?
This is my sound section in the config, screenshot [https://ptpb.pw/Iupj](url)
There is nothing else to do anymore in 4.13, just disable new, enable old.

> I like your package very much but my CB3-111 won't suspend correctly with it (no idea why -- it just works on stock kernel without reconfiguring anything), so I am trying to compile my own kernel with bare minimum modification of stock config (yes, lots of bloat drivers) to make sound output work.

Someone else mentioned suspend worked in 4.9 but not newer, I'm not sure why, the config is the same basically.  I tested it on my Toshiba CB2 with RW Legacy bios and it never worked, but flashing the UEFI rom from MrChromebox fixed that, and it boots little faster too, I recommend it.

**Comment by wheeskers** [comment] 2017-10-11 11:57
>Yeah the kernel has been broken for AGES, but at least it no longer needs patches, they've been merged. 

Yes, I've found a mail list discussion first before I've discovered your kernel for Arch and it seems that common approach is to disable everything except this broken driver.

>Files used to build are hosted in the AUR
>But I can add the config here.

I got `PKGBUILD` and your `config.x86_64` from AUR, that's right. Hosting kernel config on GH will benefit others who are not familiar with AUR or ABS. Not a big deal, don't get me wrong -- it's just more searchable and a good place to make a git pull request.

>The card is detected then?

Yep. It's detected and even `dmesg` error message is the same as with your kernel.

>What version of pulseaudio (what OS for that matter) you using?

Can't check right now but it is latest available in Arch (I did a full update last weekend).

>This is my sound section in the config, screenshot https://ptpb.pw/Iupj
>There is nothing else to do anymore in 4.13, just disable new, enable old.

That's what I did first, `CODEC drivers` are disabled, too. My process is:

1. Take `config.x86_64` from Arch stock kernel and place it as `.config` to kernel.org kernel sources;
2. Exec `make oldconfig`;
3. Run `make menuconfig` and disable everything in `ALSA for SoC audio support` except `MAX98090`;
4. Disable everything in `CODEC drivers` (as I've seen in your `.config`);
5. Save and copy `.config` to Arch stock kernel package sources;
6. Change prefixes, `updpkgchecksums`, etc;
7. Build package with `makepkg -s`.

Kernel sources are the same version at steps 1, 5-7.

The process is pretty straightforward but I still get different result when switching between this compiled kernel and your package's kernel.

>flashing the UEFI rom from MrChromebox fixed that, and it boots little faster too, I recommend it.

Good point but there are no problems with suspend on stock `4.15.x` kernels (same environment, same laptop).

**Comment by duffydack** [comment] 2017-10-11 12:22
If you're using PKGBUILD and makepkg and you have your custom config placed in same folder as pkgbuild named ".config" it won't get used.  The pkgbuild copies config.x86_64 to .config

``cp -Tf ../config.${CARCH} .config
``

I've checked Arch's configs and the suspend stuff is exactly the same, so I'm baffled to why it won't work.. I'll try look into it when I get time.

**Comment by wheeskers** [comment] 2017-10-11 12:37
>and you have your custom config placed in same folder as pkgbuild named ".config" it won't get used. 

Sure thing. I am renaming files accordingly to their build environment (i.e. `makepkg` or `make <target>`). Build kernel differs from stock one as I change options so files are OK ✔️ 

>I've checked Arch's configs and the suspend stuff is exactly the same, so I'm baffled to why it won't work.. I'll try look into it when I get time.

Thanks. I'll try to make everything from scratch once again with only SND SoC/CODECs are disabled for newest sources and see if this works for them.

**Comment by duffydack** [comment] 2017-10-11 12:45
That would have explained your sound (seemingly) being detected and showing sound output but no actual audible output, as that's the behaviour when the newer (incompatible) driver is being used in 4.13.

I have compiled using stock arch 4.13.5 config, with all sound (except old max98090) sound disabled
https://drive.google.com/drive/folders/0B_M5BSg_FZkxTng5czduR0oyWTQ?usp=sharing

**Comment by wheeskers** [comment] 2017-10-11 13:05
@duffydack, this follows my steps (allstock w/o sound except `max98090`) and uses the same version.
Does it work on your CB3-111? If yes, can you share {{config.x86_64}} for that package? I'll run a diff and see what did I do wrong then.

Thanks again for fast reply and sharing you experience with this botched driver.

**Comment by duffydack** [comment] 2017-10-11 13:12
I don't have a cb3-111, only toshiba cb2.  I can't even test it on my toshiba as I'm not using BIOS (which had the suspend problem when I tested it).  It's just for you to test.

**Comment by duffydack** [comment] 2017-10-11 13:16
Did you try my LTS version?

**Comment by wheeskers** [comment] 2017-10-11 13:29
>I don't have a cb3-111, only toshiba cb2. 

Ugh, that may be the case. Not sure why but I've thought that your CB is CB3-111. They share the same sound chip and chipset though, that's good.

I am not digging into BIOS/UEFI right now (but I am planning flash UEFI later).

>Did you try my LTS version?

Nope, just regular one. 

Well, I suggest to make a clear experiment then, if you have the time: could you please compile latest stock kernel with bare minimum SND-related changes and check if it work on Toshiba? If yes -- throw me a config and I compile it on my machine and test if it works on CB3-111.

If yes, than I can `diff` and see what was wrong earlier and we can be sure that only "ALSA for SoC" modifications are enough to make this thing work (at least for now) both on CB2 *and* CB3-111.

Thanks again and sorry to bother you with this. You are very helpful.

**Comment by duffydack** [comment] 2017-10-11 14:02
They are the same baytrail chipset like others.  My config is a very minimal config, I've disabled a lot of stuff but nothing to do with suspend which puzzles me if you say stock arch kernel works.  Like I said, I'd tried suspend with my kernel using BIOS before and had trouble, but none with UEFI. 

I have already compiled using stock ARCH config, with JUST sound changes, nothing else, it's linked above (google drive).  I don't need to test it, I know it works because that's all that's needed for working sound.  Anything else I changed was to make quicker compile and smaller size.

**Comment by wheeskers** [comment] 2017-10-11 14:11
@duffydack, got it. I'll try these on CB3-111 when I get back home.

**Comment by duffydack** [comment] 2017-10-11 14:41
Test the kernel I uploaded to google drive,  see if suspend works as I've used stock arch config and only disabled sound drivers.  If suspend works then we'll have to figure out what the main difference is.  I already have another ready for you to test with more drivers disabled and only needed drivers for video, sound, wireless to work.  Nowhere near the same minimal config I use now, but it's a good place to start, and if I can get it under 50mb I may use that for future compiles to avoid any problems with other models.

**Comment by wheeskers** [comment] 2017-10-11 15:05
>What exactly happens when you suspend anyway?

When I close the lid, it seems that suspend triggers normally (screen off, LED orange blink starts).
At the wake up resume does not happen and the whole system restarts instantly following common boot up cycle.

**Comment by duffydack** [comment] 2017-10-11 15:08
Same as mine using RW Legacy I think.. I ran systemctl suspend and power button light flashed like it was suspending, but machine ended up rebooting.

**Comment by duffydack** [comment] 2017-10-11 15:44
Ok this is interesting.  I tested these kernels done today, and I have no sound output.  This is very odd, as there is nothing else to do but disable the newer drivers so the old one builds (it fails to compile otherwise)....
I'll get back to you

**Comment by duffydack** [comment] 2017-10-11 18:32
Well this is fubar.  I've compiled about 4 kernels, all with fewer and fewer drivers and it's still getting no sound.  There is another odd thing, there is a weird bug when sound does work, when you have pulseaudio  profile (in pavucontrol) set to stereo-output + stereo input and you plug in a headset, it causes sound distotions and journal logs get spammed with "PLL unlock" messages.  Well with sound not working this isn't happening.  
From day one I started with the 4.9 kernel ( before it was LTS) and stock arch config, and all I used to change was disabling ATI/Nvidia gpu drivers and disabling all but the old max98090 driver, plus had 1 patch to apply to revert a commit in 1 of the src files which is no longer needed as it was fixed upstream.  Since then, I've been using the same config, slowly shrinking it, with no sound issues, and every new kernel release just copying over the old config and adding any new config options that came with them (during make nconfig), and everything has been working the same all this time.   I find it very odd that I can no longer get a 'stock' kernel to work.  I'm starting from scratch (make localmodconfig) with a basic config to see if that works and build from there.  I'll let you know.

**Comment by duffydack** [comment] 2017-10-11 18:50
Well, with a config made with just make localmodconfig, sound works as normal.  Now I'm back to removing more drivers (usb sound support for instance) as all that stuff was disabled.  I suggest you build your kernel upon a minimal localmodconfig, see if sound and suspend works and go from there.

**Comment by wheeskers** [comment] 2017-10-12 21:24
@duffydack, sorry for late reply, got busy.

>Well this is fubar. I've compiled about 4 kernels, all with fewer and fewer drivers and it's still getting no sound. 

Can configm. Just compiled `4.13.5` kernel from scratch with only codecs/snd drivers related sectuion changes and result is the same -- the cards is detected but output stays silent. 
Config: [config.x86_64.txt](https://github.com/duffydack/linux-max98090/files/1380728/config.x86_64.txt)

>Well, with a config made with just make localmodconfig, sound works as normal. I suggest you build your kernel upon a minimal localmodconfig, see if sound and suspend works and go from there.

Good point, thanks. Just started compilation now, I'll post back if this works (or not).

**Comment by duffydack** [comment] 2017-10-12 23:05
I've been diff'ing my config and stock config and I can't for the life of me see anything to affect it.  I've looked mainly around the i2c, gpio, pinctrl and acpi stuff, and while I found a couple of lines not present in my config, I made the modifications and compiled with the same results.  I'm wondering if this is a pulseaudio issue, as they have made some modifications since v11 (which had to be modified again (v11.1) to fix my sound.  This chip has been dogged with issues since day 1 (garbled sound on headset insertion is STILL an issue) and until the kernel/alsa devs stop supporting it as legacy and update it then it's just fubar.  It 'works' well enough for me, so I give up.  If you figure it out be sure to let me know..

**Comment by wheeskers** [comment] 2017-10-13 00:18
Finished building up what I've got using `localmodconfig`.
Process:
1. Fetch all loaded modules using `lsmod` to `modulest.list`;
2. Run `LSMOD=modules.list make localmodconfig`;
3. Interestingly, this does not work -- some other SoC audio drivers were *enabled*, I re-configured this and disabled all other drivers (ha, classic!);
4. Sound cards detected, boot up is OK;
5. Sound works but I got the same problem as you with headphone jack (jammed sound when switching).

**Summary:**
A. To get sound working, general steps for current kernel `4.13.5`:
1. Collect loaded modules, `make localmodconfig` (my results --[file](https://github.com/duffydack/linux-max98090/files/1381079/modules.list.txt));
2. Disable all SoC audio or codecs except notorious `max98090` (my results -- [file](https://github.com/duffydack/linux-max98090/files/1381080/config.x86-64.localmod.txt));
3. Double check step2, compile.

B. No idea what idea what's wrong with *suspending*, it just does not work. I'll try to enable all reasonable ACPI things and check this out again.

C. Not tested UEFI yet, will try tomorrow or at the weekend.

P.S.: PulseAudio does not seems to be related in any way (at least it did not interfere at all), at least for me.

**Comment by duffydack** [comment] 2017-10-13 08:43
You don't need to lsmod, make localmodconfig detects itself what your system has, just make sure you have everything plugged in/on that you use.  
As for the garbled output, it's only a problem with input/mic enabled, so in pavucontrol just set profile to Stereo Output and it won't happen.  I mention PA because it's had it's own problems with this card in the past basically because the card is missing a 'front' definition and PA adopts a fallback method.  

Hopefully, since they merged the patches to fix regression, they'll give it a proper final fix - it took 7 kernel versions to get this far!

As for UEFI, do eet.  Easy as pie, and your problem will just go away.

**Comment by wheeskers** [comment] 2017-10-13 10:30
>You don't need to lsmod, make localmodconfig detects itself what your system has, just make sure you have everything plugged in/on that you use.

It's just more convenient as I don't keep sources/build on target machine. Just `lsmod`-ed and compiled on better notebook with `-j4`.

>As for the garbled output, it's only a problem with input/mic enabled, so in pavucontrol just set profile to Stereo Output and it won't happen. I mention PA because it's had it's own problems with this card in the past basically because the card is missing a 'front' definition and PA adopts a fallback method.

Oh, thanks for the tip! I've solved this just by waiting for 30-40 seconds and it becomes normal again (weird).

>Hopefully, since they merged the patches to fix regression, they'll give it a proper final fix - it took 7 kernel versions to get this far!

Hope so. It would be great to use stock kernel again (I'm not saying custom is bad but it is just more convenient to update this way).

>As for UEFI, do eet. Easy as pie, and your problem will just go away.

I'd test it but I have my MMC partitioned for GPT-BIOS setup and now I need to reinstall OS with proper GPT-UEFI partitioning/boot. Post back if suspend works after I reinstall everything again (I do not want to mess with backup as I have nothing critical on that machine).

**Comment by duffydack** [comment] 2017-10-13 10:44
> It's just more convenient as I don't keep sources/build on target machine. Just lsmod-ed and compiled on better notebook with -j4.

Ah ok.  Use distcc and use your chromebook to compile as well, I compile with 3 crappy laptops, brings the time right down.

> Oh, thanks for the tip! I've solved this just by waiting for 30-40 seconds and it becomes normal again (weird).

Doesn't autofix itself for me.  I either set to output only, or switch profiles a few times before it gets a lock again (see journal for PLL unlock spam messages)

> I'd test it but I have my MMC partitioned for GPT-BIOS setup and now I need to reinstall OS with proper GPT-UEFI partitioning/boot. Post back if suspend works after I reinstall everything again (I do not want to mess with backup as I have nothing critical on that machine).

I always use a fat32 boot partition regardless, just for compat sakes.  Meant it was trivial for me to switch to uefi.  Bonus with using uefi is you get a proper console framebuffer output, so I enabled BOOT LOGO in kernel, with my own logo :)

**Comment by duffydack** [comment] 2017-10-14 19:55
Just checked something in the LTS config.  Can you test my LTS kernel to see if suspend works?

**Comment by duffydack** [comment] 2017-10-15 15:24
Well well.  I just built 4.14rc4 with a default config, with just max98090 driver enabled and sound works.  4.14 will be LTS too, and I hope there's a permanent fix for sound in there too...     I'll compile a totally default 4.14rc5 when it's available later as a test to see if sound drivers need enabling/disabling at all.. (you never know)

**Comment by wheeskers** [comment] 2017-10-15 23:52
@duffydack, sorry for the late reply, got busy for last couple of days.

Thanks for the `distcc` tip, I'll check this out. As for now, "clean" (using `lsmod` list) kernel compilation about ~20 minutes (not that fast but OK).

> journal for PLL unlock spam messages

Same thing. But waiting or pause-play-pause do fix this (again, weird).

>Meant it was trivial for me to switch to uefi. Bonus with using uefi is you get a proper console framebuffer output, so I enabled BOOT LOGO in kernel, with my own logo :)

Nice bonus! I've installed MrChromebox's UEFI firmware without any problems **but** it tooks me at least 3 hours to determine what's wrong with bootloaders (GRUB, EFISTUB, rEFInd won't work as additional boot options, reboot always drops to embedded UEFI shell).

Boot options **editing** is also not supported in `persistent` mode using `efibootmgr` or even full UEFI v2 Shell (loaded as additional `*.efi` application on ESP).

Thanks to this [Reddit thread](https://www.reddit.com/r/chrultrabook/comments/5aakcy/mrchromebox_full_rom_uefi_mode_not_saving_boot/) I've finally got it working.

>Well well. I just built 4.14rc4 with a default config, with just max98090 driver enabled and sound works

Just by disabling other SND drivers and without other modification of stock config?

**Comment by duffydack** [comment] 2017-10-15 23:59
I just use system-boot, pretty simple and works.

Yes, stock config with only sound modifications.

**Comment by wheeskers** [comment] 2017-10-16 00:23
>Yes, stock config with only sound modifications.

Good news! Much better than having to play hide-and-seek with kernel options that *may* affect this driver.

>I just use systemd-boot, pretty simple and works.

But did you add a new boot option? Or this just works out-of-the-box?

-----

BTW, your latest kernel works great with `systemctl suspend`, thanks again for that suggestion. No idea what was wrong with `RW_LEGACY` BIOS boot and suspend operation but at lest this just works on UEFI.

**Comment by duffydack** [comment] 2017-10-16 08:40
> Good news! Much better than having to play hide-and-seek with kernel options that may affect this driver.
I noticed in my LTS config I had CONFIG_MFD_CROS_EC set, but not set in the main linux config.  We don't use chromeOS anymore, but, it does mention 'power saving', so that might be something to look at to get suspend working properly on Bios... I'll make sure to add it in future, it can't hurt.

> But did you add a new boot option? Or this just works out-of-the-box?
With systemd-boot (used to be gummiboot) you have to add the entry yourself.  There are examples to use in /usr/share/systemd/bootctl

> /boot/loader/entries/archmax.conf (using luks and systemd mkinit hook)
title   Arch (byt-max98090)
linux   /vmlinuz-linux-max98090
initrd  /intel-ucode.img
initrd  /initramfs-linux-max98090.img
options rd.luks.uuid=2e5420db-f132-4b7a-b7c2-9b82550ea5aa root=UUID=20e4f650-13d1-4ea6-9d2d-02b1d112de9d systemd.gpt_auto=0 pci=noaer rw

**Comment by wheeskers** [comment] 2017-10-16 11:00
I've realized why `systemd-boot` works out of the box (initial launch, not speaking about multiple kernel images) on your machine. It places EFI loader application to `esp/EFI/Boot/BOOTX64.EFI`  by default and the same path is seems to be *hardcoded* in MrChromebox's compiled UEFI firmware.

This works as some kind of "conventional workaround" or may be specially selected to make `systemd-boot` work. I've managed to launch other bootloaders just by copying their main application file to `esp/EFI/Boot/BOOTX64.EFI `.

BTW, on my other laptop `EFIVARS` are available with persistent `rw` mode and `efibootmgr` can add **and** save boot options directly to NVRAM (cool feature but requires "standard" UEFI). This basically works without any bootloaders at all (other laptop from the same vendor, however, has awful EFI-BIOS non-standard mix and it won't dual-boot with anything except `syslinux` and EFI-BIOS plus MBR partitioning).

>I noticed in my LTS config I had CONFIG_MFD_CROS_EC set, but not set in the main linux config. We don't use chromeOS anymore, but, it does mention 'power saving', so that might be something to look at to get suspend working properly on Bios... I'll make sure to add it in future, it can't hurt.

Great tip. I have an error/warning when booting current stock kernel like `cros_ec not available` (or something like this, can't check right now), this may solve this as well.

**Comment by duffydack** [comment] 2017-10-16 11:08
> Great tip. I have an error/warning when booting current stock kernel like cros_ec not available (or something like this, can't check right now), this may solve this as well.

CONFIG_MFD_CROS_EC=m
CONFIG_MFD_CROS_EC_I2C=m 
are both enabled by default in stock.  dunno if it will make any difference.

I didn't have any issues with switching to systemd-boot (I use it on 2 other machines).  Simple bootctl --path=/boot install did the job no fuss.

**Closed** 2017-10-21 11:04 UTC

**Comment by duffydack** [comment] 2017-11-19 23:23
So...... I started from a default config for 4.14, did everything I normally do, and had the same muted sound you did.  So something new in the config is fucking it up, but nothing I can immediately find to do with acpi, gio, pinctrl etc.  So I did some digging, and found this to be the culprit (as far as 4.14 goes)

![1](https://user-images.githubusercontent.com/20307378/32996878-961622c2-cd80-11e7-956d-22fc4d3f6ef7.png)
CONFIG_INTEL_ATOMISP

Give it a try, let me know

**Comment by wheeskers** [comment] 2017-11-20 14:33
@duffydack, thank you for keep looking into this.
I'll check this setup on CB3-111 with kernel `4.14` and post back my results.

**Comment by wheeskers** [comment] 2017-11-21 20:13
@duffydack,

I've tried your suggestion, just compiled `4.14` kernel with disabled sound drivers/codecs (except `max98090` of course) and disabled `CONFIG_INTEL_ATOMISP` -- this setup works on my CB3-111, too.

Sound is muted by default (Left/Right Mixer DACs) but it works once unmuted via  `alsamixer`.
Thanks! I guess this setup is OK for `4.14` but no idea if this will work for newer kernels in the future.

**Comment by duffydack** [comment] 2017-11-21 20:46
older hardware and newer kernels sometimes don't play nice.  I have a rubbish asus laptop that does not like anything newer than 4.9.  It hangs while booting.  I can get it to work with certain kernel boot parameters but it's not worth the hassle.  Well at least 4.14 is LTS and works, so we're good for a few years, if our chromebooks last that long.

**Comment by wheeskers** [comment] 2017-11-22 00:37
>older hardware and newer kernels sometimes don't play nice. I have a rubbish asus laptop that does not like anything newer than 4.9.

I have a weird luck: my older laptops always were fine with fresh kernels (i.e. Lenovo B560 from 2011 or Asus eeePC 1015 from 2009), everything just works out-of-the box. Let's hope `4.15` and next LTS will work for our Chromeboox as well.
